//! Stands in for perl where kbuild runs lib/build_OID_registry, and refuses
//! anything else, so a second perl script cannot pass unnoticed.

const std = @import("std");

const Entry = struct {
    name: []const u8,
    octets: []const u8,
    hash: u8,
    index: usize,
};

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const arena = init.arena.allocator();
    const argv = try init.minimal.args.toSlice(arena);
    if (argv.len != 4) return error.Usage;

    const script, const in, const out = .{ argv[1], argv[2], argv[3] };
    if (!std.mem.eql(u8, std.fs.path.basename(script), "build_OID_registry")) return error.UnknownScript;

    const cwd = std.Io.Dir.cwd();
    const source = try cwd.readFileAlloc(io, in, arena, .limited(1 << 24));

    var entries: std.ArrayList(Entry) = .empty;
    var total: usize = 0;
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |line| {
        const found = parse(line) orelse continue;
        const octets = try encode(arena, found.oid);
        try entries.append(arena, .{
            .name = found.name,
            .octets = octets,
            .hash = hash(octets),
            .index = total,
        });
        total += octets.len;
    }

    var c: std.Io.Writer.Allocating = .init(arena);
    const w = &c.writer;

    try w.print("/*\n * Automatically generated by {s}.  Do not edit\n */\n", .{
        try relative(io, arena, init.environ_map, script),
    });

    try w.print("\nstatic const unsigned {s} oid_index[OID__NR + 1] = {{\n", .{
        if (total <= 255) "char" else "short",
    });
    for (entries.items) |entry| try w.print("\t[OID_{s}] = {d},\n", .{ entry.name, entry.index });
    try w.print("\t[OID__NR] = {d}\n}};\n", .{total});

    try w.print("\nstatic const unsigned char oid_data[{d}] = {{\n", .{total});
    for (entries.items) |entry| {
        try w.writeByte('\t');
        for (entry.octets) |octet| try w.print("{d}, ", .{octet});
        try w.print("\t// {s}\n", .{entry.name});
    }
    try w.writeAll("};\n");

    const order = try arena.dupe(Entry, entries.items);
    std.mem.sort(Entry, order, {}, before);

    try w.print("\nstatic const struct {{\n\tunsigned char hash;\n\tenum OID oid : {d};\n}} oid_search_table[OID__NR] = {{\n", .{
        if (entries.items.len - 1 <= 255) @as(u8, 8) else 16,
    });
    for (order, 0..) |entry, i| {
        try w.print("\t[{d: >3}] = {{ {d: >3}, OID_{s: <35} }}, // ", .{ i, entry.hash, entry.name });
        for (entry.octets) |octet| try w.print("{x:0>2}", .{octet});
        try w.writeByte('\n');
    }
    try w.writeAll("};\n");

    try cwd.writeFile(io, .{ .sub_path = out, .data = c.written() });
}

fn parse(line: []const u8) ?struct { name: []const u8, oid: []const u8 } {
    const start = std.mem.indexOf(u8, line, "OID_") orelse return null;
    if (start == 0 or !std.ascii.isWhitespace(line[start - 1])) return null;

    var i = start + "OID_".len;
    if (i >= line.len or line[i] < 'A' or line[i] > 'z') return null;
    const name = i;
    while (i < line.len and (std.ascii.isAlphanumeric(line[i]) or line[i] == '_')) i += 1;
    if (i == name + 1) return null;
    const end = i;

    if (i >= line.len or line[i] != ',') return null;
    i = skip(line, i + 1) orelse return null;
    if (!std.mem.startsWith(u8, line[i..], "/*")) return null;
    i = skip(line, i + "/*".len) orelse return null;

    if (line[i] != '0' and line[i] != '1' and line[i] != '2') return null;
    const oid = i;
    while (i < line.len and (std.ascii.isDigit(line[i]) or line[i] == '.')) i += 1;
    const stop = i;

    i = skip(line, i) orelse return null;
    if (!std.mem.startsWith(u8, line[i..], "*/")) return null;

    return .{ .name = line[name..end], .oid = line[oid..stop] };
}

fn skip(line: []const u8, from: usize) ?usize {
    var i = from;
    while (i < line.len and std.ascii.isWhitespace(line[i])) i += 1;
    return if (i == from or i >= line.len) null else i;
}

fn encode(arena: std.mem.Allocator, oid: []const u8) ![]const u8 {
    var octets: std.ArrayList(u8) = .empty;
    var components = std.mem.splitScalar(u8, oid, '.');
    const first = try std.fmt.parseInt(u32, components.next() orelse return error.BadOid, 10);
    const second = try std.fmt.parseInt(u32, components.next() orelse return error.BadOid, 10);
    try octets.append(arena, @intCast(first * 40 + second));

    while (components.next()) |component| {
        const value = try std.fmt.parseInt(u32, component, 10);
        var shift = width(value) / 7;
        while (shift > 0) : (shift -= 1)
            try octets.append(arena, @intCast((value >> @intCast(shift * 7)) & 0x7f | 0x80));
        try octets.append(arena, @intCast(value & 0x7f));
    }
    return octets.items;
}

fn width(value: u32) u32 {
    return if (value == 0) 0 else 31 - @clz(value);
}

fn hash(octets: []const u8) u8 {
    var sum: i64 = @as(i64, @intCast(octets.len)) - 1;
    for (octets) |octet| sum += @as(i64, octet) * 33;
    sum = (sum >> 24) ^ (sum >> 16) ^ (sum >> 8) ^ sum;
    return @intCast(sum & 0xff);
}

fn before(_: void, a: Entry, b: Entry) bool {
    if (a.hash != b.hash) return a.hash < b.hash;
    if (a.octets.len != b.octets.len) return a.octets.len < b.octets.len;
    var i = a.octets.len;
    while (i > 0) {
        i -= 1;
        if (a.octets[i] != b.octets[i]) return a.octets[i] < b.octets[i];
    }
    return false;
}

fn relative(io: std.Io, arena: std.mem.Allocator, env: *const std.process.Environ.Map, path: []const u8) ![]const u8 {
    const srctree = env.get("srctree") orelse return path;
    const root = std.Io.Dir.cwd().realPathFileAlloc(io, srctree, arena) catch return path;
    const prefix = try std.fmt.allocPrint(arena, "{s}/", .{root});
    return if (std.mem.startsWith(u8, path, prefix)) path[prefix.len..] else path;
}
